### ISSUE TITLE
EEXIST

### ISSUE THREAD

**Issue by nitrag** [TheSmiths/ti.es6#7]
Error on compile.

```
[DEBUG] :  Creating /Users/ryan/Documents/Appcelerator_Studio_Workspace/ParseES6/build/iphone
[INFO] :   Preparing project for ES6.
[ERROR] :  Error: EEXIST, mkdir '/Users/ryan/Documents/Appcelerator_Studio_Workspace/ParseES6/.project'
    at Error (native)
[ERROR] :  An error occurred during build after 91ms
[ERROR] :  Unable to use ES6
2016-02-17T18:46:56.642Z | TRACE  | titanium exited with exit code 1
2016-02-17T18:46:56.642Z | ERROR  | Error: ti run exited with error code 1
    at ChildProcess.<anonymous> (/Users/ryan/.appcelerator/install/5.1.0/package/node_modules/appc-cli-titanium/plugins/run.js:92:66)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
2016-02-17T18:46:56.643Z | TRACE  | Sending exit signal to titanium process:  76248
```

**Comment by nuno** [comment]
Same here! I have to rename the file  ".project" then works.
